"""fdldjksfhg

Revision ID: 047963e1bf5c
Revises: bf4f20df22c6
Create Date: 2025-10-07 20:52:10.029205

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '047963e1bf5c'
down_revision: str | Sequence[str] | None = 'bf4f20df22c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=4096), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipient_id', 'messages', ['recipient_id'], unique=False)
    op.create_index('idx_sender_id', 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sender_id', table_name='messages')
    op.drop_index('idx_recipient_id', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
