# Generated by Django 5.2.4 on 2025-08-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_tag_alter_comment_text_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="posts.tag", verbose_name="Теги"
            ),
        ),
    ]
