# Generated by Django 5.2.4 on 2025-08-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, max_length=512, null=True, upload_to="%Y/%m/%d"
            ),
        ),
    ]
