FROM python:3.13.9-alpine

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# 0. Создание рабочей директории и переход в неё.
WORKDIR /app

# 0. Установка UV.
ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh

ENV PATH="/root/.local/bin/:$PATH" \
    UV_PYTHON=python3.13 \
    UV_PYTHON_DOWNLOADS=never \
    UV_PROJECT_ENVIRONMENT=/app/venv \
    UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1

COPY pyproject.toml uv.lock /app/

# 1. Установка зависимостей.

RUN uv sync --no-dev --no-install-project --frozen --no-cache

# 3. Копирование файлов проекта.
COPY . .
