# Generated by Django 5.2.4 on 2025-07-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="note",
            table="notes",
        ),
    ]
