# Generated by Django 5.2.4 on 2025-08-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователя",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Телефон в формате только цифр",
                max_length=15,
                null=True,
                verbose_name="Телефон",
            ),
        ),
    ]
