# Generated by Django 5.2.4 on 2025-08-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Тег",
                    ),
                ),
            ],
            options={
                "db_table": "tags",
            },
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.CharField(max_length=4096, verbose_name="Текст комментария"),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="posts.tag", verbose_name="Теги"),
        ),
    ]
