name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    services:
      db:
        image: redis:latest
        ports:
          - "6379:6379"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}
        python-version-file: "Django_REST/pyproject.toml"

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run Tests
      run: |
        cd Django_REST
        uv run python manage.py test
